entity.demo_formation_config_entity.list:
  path: '/admin/config/system/demo_formation_config_entity'
  defaults:
    _entity_list: 'demo_formation_config_entity'
    _title: 'Example Configuration'
  requirements:
    _permission: 'administer site configuration'
entity.demo_formation_config_entity.add_form:
  path: '/admin/config/system/demo_formation_config_entity/add'
  defaults:
    _entity_form: 'demo_formation_config_entity.add'
    _title: 'Add demo_formation_config_entity'
  requirements:
    _permission: 'administer site configuration'
entity.demo_formation_config_entity.edit_form:
  path: '/admin/config/system/demo_formation_config_entity/{demo_formation_config_entity}'
  defaults:
    _entity_form: 'demo_formation_config_entity.edit'
    _title: 'Edit demo_formation_config_entity'
  requirements:
    _permission: 'administer site configuration'
entity.demo_formation_config_entity.delete_form:
  path: '/admin/config/system/demo_formation_config_entity/{demo_formation_config_entity}/delete'
  defaults:
    _entity_form: 'demo_formation_config_entity.delete'
    _title: 'Delete demo_formation_config_entity'
  requirements:
    _permission: 'administer site configuration'
