<?php
use Drupal\Core\Access\AccessResult;

function demoformation_theme($existing, $type, $theme, $path){
  return array(
    'liste_commercant_fivory' => array(
      'variables' => array('
      ' => array())
    )
  );
}

function demoformation_node_access(\Drupal\node\NodeInterface $node, $operation, \Drupal\Core\Session\AccountInterface $account){
  if($node->bundle() == 'article'){
    switch($operation){
      case 'view':
        return
        AccessResult::allowedIfHasPermission($account, 'administer api url');
      case 'create':
        if($account->hasPermission('administer api url', $account)){
            return AccessResult::allowed()->cachePerPermissions();
        }
        else {
          return AccessResult::forbidden()->cachePerPermissions();
        }
      default:
        return AccessResult::neutral();
    }
  }
}

function demoformation_form_alter(&$form, &$form_state ){
  if (($form['#form_id'] == 'node_article_form') || ($form['#form_id'] == 'node_article_edit_form')){
    die(var_dump('fklfls'));
    $form['title']['widget']['#description'] = t('Le titre de votre contenu');
    $form['#validate'][] = 'my_custom_gdshdsfh';
  }
}

function my_custom_gdshdsfh($form, $form_state){
  if ($form_state->getValue('title') != 'Titre'){
    $form_state->setErrorByName('title', t('Le titre n\'est pas valide'));
  }
}
